version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5000  # Backend URL inside the Docker network
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mongodb://mongo:27017/geoData
    depends_on:
      - mongo
    networks:
      - app-network
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo-data:/data/db
      - ./data/features.json:/data/features.json  # Mount GeoJSON file for population
    networks:
      - app-network
    command: ["mongod"]  # Default MongoDB command (no need for --bind_ip_all)

  data_population:
    build:
      context: ./backend
    environment:
      - DATABASE_URL=mongodb://mongo:27017/geoData
    depends_on:
      - mongo
    command: ["node", "populateFeatures.js"]  # Populate MongoDB with initial data once
    networks:
      - app-network
    restart: "no"  # Ensure this runs only once, then stops

volumes:
  mongo-data:
    driver: local

networks:
  app-network:
    driver: bridge
